---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maneletorres/Microservices-with-Spring-Cloud
          search-paths: ConfigData
server:
  port: 8001